---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Vagrant up
inputs:
  memory:
    description: 'Memory'
    default: 12288
  cpu:
    description: 'CPU'
    default: 3

runs:
  using: "composite"
  steps:
    - name: Run vagrant box instance
      shell: bash
      env:
        VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
        MEMORY: ${{ inputs.memory }}
        CPUS: ${{ inputs.cpu }}
      run: vagrant up
