---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: regional
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 10.128.0.0/12
  topology:
    class: quick-start
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
      - name: imageRepository
        value: ""
      - name: etcdImageTag
        value: ""
      - name: coreDNSImageTag
        value: ""
      - name: podSecurityStandard
        value:
          audit: restricted
          enabled: false
          enforce: baseline
          warn: restricted
    version: v1.27.1
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
